FROM ghcr.io/xip-online-applications/php-docker-containers/php-dev:8.5-fpm AS base

COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-amqp:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-bcmath:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-composer:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-curl:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-datadog:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-gd:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-imagick:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-intl:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-mbstring:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-mongodb:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-mysql:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-nodejs:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-opcache:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-pcov:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-pcntl:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-pgsql:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-rdkafka:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-redis:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-saxonc:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-soap:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-sockets:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-xdebug:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-xml:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-xsl:8.5 /opt /opt
COPY --from=ghcr.io/xip-online-applications/php-docker-containers/php-dev-extra-zip:8.5 /opt /opt
