name: Create and publish base container reusable workflow.

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      release:
        required: true
        type: string

jobs:
  base:
    uses: ./.github/workflows/build-wf.yaml
    with:
      registry: ghcr.io
      actor: ${{ github.actor }}
      command: "make release-base-${{ inputs.base }} RELEASE=${{ inputs.release }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
