name: Create and publish base container reusable workflow.

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      release:
        required: true
        type: string
      actor:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  base:
    uses: ./.github/workflows/build-wf.yaml
    with:
      registry: ghcr.io
      actor: ${{ inputs.actor }}
      command: "make release-base-${{ inputs.base }} RELEASE=${{ inputs.release }}"
    secrets:
      token: ${{ secrets.token }}
