name: Create and publish extension container reusable workflow.

on:
  workflow_call:
    inputs:
      extension:
        required: true
        type: string
      release:
        required: true
        type: string
      stage:
        required: true
        type: string
      actor:
        required: true
        type: string
    secrets:
      token:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-extension-wf
  cancel-in-progress: true

jobs:
  extensions:
    uses: ./.github/workflows/build-wf.yaml
    with:
      name: ${{ inputs.extension }}
      registry: ghcr.io
      actor: ${{ inputs.actor }}
      command: "make -j4 ${{ inputs.stage }}-extension-${{ inputs.extension }} RELEASE=${{ inputs.release }}"
    secrets:
      token: ${{ secrets.token }}
