name: Create and publish base containers.

on:
  workflow_call:
    inputs:
      registry:
        default: ghcr.io
        type: string
      release:
        required: true
        type: string
      actor:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    name: "Build container"
    uses: ./.github/workflows/build-wf.yaml
    with:
      registry: ${{ inputs.registry }}
      actor: ${{ inputs.actor }}
      command: "make release-base-build RELEASE=${{ inputs.release }}"
    secrets:
      token: ${{ secrets.token }}

  fpm:
    name: "FPM container"
    needs: build
    uses: ./.github/workflows/build-wf.yaml
    with:
      registry: ${{ inputs.registry }}
      actor: ${{ inputs.actor }}
      command: "make release-base-fpm RELEASE=${{ inputs.release }}"
    secrets:
      token: ${{ secrets.token }}
