name: Create and publish extension container reusable workflow.

on:
  workflow_call:
    inputs:
      extension:
        required: true
        type: string
      release:
        required: true
        type: string
      actor:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  extensions:
    uses: ./.github/workflows/build-wf.yaml
    with:
      registry: ghcr.io
      actor: ${{ inputs.actor }}
      command: "make release-extension-${{ inputs.extension }} RELEASE=${{ inputs.release }}"
    secrets:
      token: ${{ secrets.token }}
