name: Create and publish base containers.

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string
      actor:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    uses: ./.github/workflows/build-base-wf.yaml
    with:
      base: build
      release: ${{ inputs.release }}
      actor: ${{ inputs.actor }}
    secrets:
      token: ${{ secrets.token }}

  fpm:
    needs: build
    uses: ./.github/workflows/build-base-wf.yaml
    with:
      base: fpm
      release: ${{ inputs.release }}
      actor: ${{ inputs.actor }}
    secrets:
      token: ${{ secrets.token }}
