name: Build the latest containers.

on:
  push:
    branches: ['main']

permissions:
  contents: read
  packages: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base:
    uses: ./.github/workflows/build-base.yaml
    with:
      release: ${{ github.sha }}
      actor: ${{ github.actor }}
      stage: dev
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  extensions:
    needs: base
    uses: ./.github/workflows/build-extensions.yaml
    with:
      release: ${{ github.sha }}
      actor: ${{ github.actor }}
      stage: dev
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  environments:
    needs: extensions
    uses: ./.github/workflows/build-environments.yaml
    with:
      release: ${{ github.sha }}
      actor: ${{ github.actor }}
      stage: dev
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
