name: Build the latest containes.

on:
  push:
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  base:
    uses: ./.github/workflows/build-base.yaml
    with:
      release: ${{ github.sha }}
      actor: ${{ github.repository_owner }}
      stage: dev
    secrets:
      token: ${{ secrets.GHCR_TOKEN }}

  extensions:
    needs: base
    uses: ./.github/workflows/build-extensions.yaml
    with:
      release: ${{ github.sha }}
      actor: ${{ github.repository_owner }}
      stage: dev
    secrets:
      token: ${{ secrets.GHCR_TOKEN }}

  environments:
    needs: extensions
    uses: ./.github/workflows/build-environments.yaml
    with:
      release: ${{ github.sha }}
      actor: ${{ github.repository_owner }}
      stage: dev
    secrets:
      token: ${{ secrets.GHCR_TOKEN }}
