name: Build the latest containes.

on:
  push:
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  base:
    uses: ./.github/workflows/build-base.yaml
    with:
      release: ${{ github.sha }}

  extensions:
    needs: base
    uses: ./.github/workflows/build-extensions.yaml
    with:
      release: ${{ github.sha }}
