name: Build the latest containes.

on:
  push:
    branches: ['main']

permissions:
  contents: read
  packages: write

jobs:
  base:
    uses: ./.github/workflows/build-wf.yaml
    with:
      registry: ghcr.io
      actor: ${{ github.actor }}
      command: "make -j 4 base RELEASE=${{ github.sha }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  extensions:
    needs: base
    uses: ./.github/workflows/build-wf.yaml
    with:
      registry: ghcr.io
      actor: ${{ github.actor }}
      command: "make -j 4 extensions RELEASE=${{ github.sha }}"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
