name: Release the containers.

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  base:
    uses: ./.github/workflows/build-base.yaml
    with:
      release: ${{ github.ref_name }}
      actor: ${{ github.repository_owner }}
      stage: release
    secrets:
      token: ${{ secrets.GHCR_TOKEN }}

  extensions:
    needs: base
    uses: ./.github/workflows/build-extensions.yaml
    with:
      release: ${{ github.ref_name }}
      actor: ${{ github.repository_owner }}
      stage: release
    secrets:
      token: ${{ secrets.GHCR_TOKEN }}

  environments:
    needs: extensions
    uses: ./.github/workflows/build-environments.yaml
    with:
      release: ${{ github.ref_name }}
      actor: ${{ github.repository_owner }}
      stage: release
    secrets:
      token: ${{ secrets.GHCR_TOKEN }}
